# Generated by Django 4.2.6 on 2023-10-30 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('content', models.TextField()),
                ('video_url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
